extensions:
  TemplateHaskell: true
  MultiParamTypeClasses: true
  DeriveDataTypeable: true
  TypeFamilies: true
  QuasiQuotes: true
  GADTs: true
  FlexibleContexts: true
  OverloadedStrings: true
cabal-file: project.cabal
extra-packages: ''
version: 1
environment: ghc-7.4.2-stable-13.09
module-template: ! 'module MODULE_NAME where

'
ghc-args: []
modules:
  Init:
    filename: src/Init.hs
  Main(src/Main.hs):
    filename: src/Main.hs
  Handler.Home:
    filename: src/Handler/Home.hs
